### ISSUE TITLE
Error on running the launch file

### ISSUE THREAD

**Issue by kiranb222** [YonoHub/waymo_ros#1]
Hi,
When I run the launch file roslaunch waymo_ros waymo_player.launch FilePath:="path/to/tffile", I get an error "cannot launch node of type [waymo_ros/waymo_rospy.py]: can't locate node [waymo_rospy.py] in package [waymo_ros]". Please help me with this.

**Comment by AhmedARadwan** [comment]
Can you provide more details on how to reproduce the same error?

**Comment by kiranb222** [comment]
Sorry @AhmedARadwan , my bad. The issue was simply due to not setting the waymo_rospy.py as executable. chmod made it work. 
However, having difficulty in running tensorflow in ros -kinetic due to python and pip version related issues. Looking into this.

**Comment by AhmedARadwan** [comment]
Sure no problem. If you have any other issues with the package, please let me know.
